### ISSUE TITLE
Invalid start byte

### ISSUE THREAD

**Issue by waggers5** [RavinMaddHatter/Structura#118]
I'm getting the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 329, in runFromGui
  File "structura.py", line 96, in generate_pack
  File "structure_reader.py", line 10, in __init__
  File "nbtlib\nbt.py", line 131, in load
  File "nbtlib\nbt.py", line 294, in from_fileobj
  File "nbtlib\tag.py", line 1043, in parse
  File "nbtlib\tag.py", line 1043, in parse
  File "nbtlib\tag.py", line 1043, in parse
  File "nbtlib\tag.py", line 885, in parse
  File "nbtlib\tag.py", line 818, in __init__
  File "nbtlib\tag.py", line 885, in <genexpr>
  File "nbtlib\tag.py", line 1043, in parse
  File "nbtlib\tag.py", line 1043, in parse
  File "nbtlib\tag.py", line 1043, in parse
  File "nbtlib\tag.py", line 722, in parse
  File "nbtlib\tag.py", line 219, in read_string
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3: invalid start byte
```

**Comment by waggers5** [comment]
Resolved - my structures contained entities. Creating the structure with the "include entities" toggle switched off is the answer.
