### ISSUE TITLE
Error when making file

### ISSUE THREAD

**Issue by KillEricsson** [RavinMaddHatter/Structura#124]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 329, in runFromGui
  File "structura.py", line 96, in generate_pack
  File "structure_reader.py", line 12, in __init__
  File "nbtlib\tag.py", line 1106, in __getitem__
KeyError: ''

**Comment by RavinMaddHatter** [comment]
Turn off entities

**Comment by KillEricsson** [comment]
It didn't help

**Comment by RavinMaddHatter** [comment]
Then check the file size and upload the file

**Comment by KillEricsson** [comment]
Nope, still not working.(
