### ISSUE TITLE
does't make the pack

### ISSUE THREAD

**Issue by idkGgg** [RavinMaddHatter/Structura#127]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 27, in generate_pack
  File "structure_reader.py", line 9, in __init__
  File "nbtlib\tag.py", line 1106, in __getitem__
KeyError: ''

**Comment by RavinMaddHatter** [comment]
They changed the file format if you have entities export enabled. When
exporting from Minecraft uncheck that setting.

If that isn't it, the most likely cause is improper install.

You need to download the zip and extract, keeping all files together

**Comment by RavinMaddHatter** [comment]
That is due to 1.19 changes
