### ISSUE TITLE
KeyError: 'piston_arm_collision'

### ISSUE THREAD

**Issue by M2DRIVE** [RavinMaddHatter/Structura#149]
Exception in Tkinter callback
Traceback (most recent call last):
  File "structura.py", line 96, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 330, in block_name_to_uv
  File "armor_stand_class.py", line 352, in get_block_texture_paths
KeyError: 'piston_arm_collision'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 99, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 330, in block_name_to_uv
  File "armor_stand_class.py", line 352, in get_block_texture_paths
KeyError: 'piston_arm_collision'

**Comment by RavinMaddHatter** [comment]
Version? Structure file?

**Comment by RavinMaddHatter** [comment]
I didn't get a version. i think this is 1.0
