### ISSUE TITLE
non-compound root tags is not supported, making it fail

### ISSUE THREAD

**Issue by mmarchjr** [RavinMaddHatter/Structura#161]
I was trying to turn an ice elevator me and my friends had made into a resource pack to build in survival, and when using this tool, it gave me this error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\Downloads\Structura-main\Structura-main\structura.py", line 153, in runFromGui
    structura_base.make_big_model()
  File "C:\Users\mmarc\Downloads\Structura-main\Structura-main\structura_core.py", line 53, in make_big_model
    struct2make=structure_reader.combined_structures(file_names,exclude_list=self.exclude_list)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\Downloads\Structura-main\Structura-main\structure_reader.py", line 74, in __init__
    self.structs[file]["nbt"] = nbtlib.load(file, byteorder='little')
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\nbt.py", line 131, in load
    return File.from_fileobj(fileobj, byteorder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\nbt.py", line 259, in from_fileobj
    self = cls.parse(fileobj, byteorder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\nbt.py", line 225, in parse
    raise TypeError(
TypeError: Non-Compound root tags is not supported: <class 'nbtlib.tag.End'>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\Downloads\Structura-main\Structura-main\structura.py", line 159, in runFromGui
    structura_base.generate_with_nametags()
  File "C:\Users\mmarc\Downloads\Structura-main\Structura-main\structura_core.py", line 79, in generate_with_nametags
    struct2make = structure_reader.process_structure(self.structure_files[model_name]["file"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\Downloads\Structura-main\Structura-main\structure_reader.py", line 20, in __init__
    self.NBTfile = nbtlib.load(file, byteorder='little')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\nbt.py", line 131, in load
    return File.from_fileobj(fileobj, byteorder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\nbt.py", line 259, in from_fileobj
    self = cls.parse(fileobj, byteorder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mmarc\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\nbt.py", line 225, in parse
    raise TypeError(
TypeError: Non-Compound root tags is not supported: <class 'nbtlib.tag.End'>
```
the file(zipped up):
[ice_elevator.zip](https://github.com/RavinMaddHatter/Structura/files/11277472/ice_elevator.zip)

**Comment by RavinMaddHatter** [comment]
![image](https://user-images.githubusercontent.com/4407668/233199422-f3852915-0033-49fb-8d24-dc491bb64bbb.png)
Your file is empty. This is likely due to an issue in minecraft related to exporting files to a onedrive folder such as my documents. 

I do have it on my list to check file size and give a different error in a future update.

**Comment by mmarchjr** [comment]
I did realize that, but once I got that fixed, it seemed to work. it won't display in my world however
