### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by Luminous-Journey** [RavinMaddHatter/Structura#201]
when trying to use program (ver. 1.6.1) I get this error
`Exception in Tkinter callback
Traceback (most recent call last):  
  File "tkinter\__init__.py", line 1921, in __call__  
  File "structura.py", line 158, in runFromGui  
  File "structura_core.py", line 79, in generate_with_nametags  
  File "structure_reader.py", line 25, in __init__  
  File "nbtlib\nbt.py", line 131, in load  
  File "nbtlib\nbt.py", line 259, in from_fileobj  
  File "nbtlib\nbt.py", line 225, in parse  
TypeError: Non-Compound root tags is not supported: <class 'nbtlib.tag.End'>
`

**Comment by Luminous-Journey** [comment]
I get the .mcstructure file in the output but not the texture pack

**Comment by RavinMaddHatter** [comment]
your structure is empy. 0kB file. The reason this occurs is due to a minecraft bug. that comes up if you export into a one drive folder.
