### ISSUE TITLE
`minecraft:red_terracotta` not supported

### ISSUE THREAD

**Issue by besidenormal** [RavinMaddHatter/Structura#216]
```
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 99, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 330, in block_name_to_uv
  File "armor_stand_class.py", line 352, in get_block_texture_paths

KeyError: 'red_terracotta'

```
I cant exactly pinpoint the exact problem at hand but this seems like the case. I'm not well versed in python or C++ so I'm not sure if this is the actual issue at hand.

**Comment by RavinMaddHatter** [comment]
I checked this si supported in the current version. you must hav ebeen using a old version
