### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Yaroslav5208** [RavinMaddHatter/Structura#218]
structura16-26082023
Exception in Tkinter callback
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1042, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000029DFECFC610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='smgafwso25.execute-api.us-east-2.amazonaws.com', port=443): Max retries exceeded with url: /default/structuraUpdate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029DFECFC610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "structura.py", line 31, in update
  File "updater.py", line 7, in update
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='smgafwso25.execute-api.us-east-2.amazonaws.com', port=443): Max retries exceeded with url: /default/structuraUpdate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029DFECFC610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by RavinMaddHatter** [comment]
Update to the latest version of structura. this is because i changed the url.
