### ISSUE TITLE
error while making pack of some mcstructure

### ISSUE THREAD

**Issue by nashubashu** [RavinMaddHatter/Structura#22]
error message:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/storage/emulated/0/CppCompiler/Structura-1.1beta/PackMaker.py", line 119, in runFromGui
    generate_pack(FileGUI.get(), packName.get())
  File "/storage/emulated/0/CppCompiler/Structura-1.1beta/PackMaker.py", line 78, in generate_pack
    armorstand.make_block(x, y, z, block["name"].replace(
  File "/storage/emulated/0/CppCompiler/Structura-1.1beta/armor_stand_class.py", line 65, in make_block
    uv = self.block_name_to_uv(block_name,variant=variant)
  File "/storage/emulated/0/CppCompiler/Structura-1.1beta/armor_stand_class.py", line 311, in block_name_to_uv
    self.extend_uv_image(
  File "/storage/emulated/0/CppCompiler/Structura-1.1beta/armor_stand_class.py", line 286, in extend_uv_image
    image_array[0:shape[0], 0:shape[1], 0:impt.shape[2]] = impt
IndexError: tuple index out of range

> 
example mcstructure

**Comment by RavinMaddHatter** [comment]
Can you get me the example strucutre? i need to see the blocks that broke so i can fix them.

**Comment by RavinMaddHatter** [comment]
I fixed a number of these for the next release, currently being tested
