### ISSUE TITLE
Failed to convert

### ISSUE THREAD

**Issue by TotallyTung** [RavinMaddHatter/Structura#235]
Exception in Tkinter callback
Traceback (most recent call last):
  File "\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "\Structura-main\structura.py", line 202, in runFromGui
    structura_base.generate_with_nametags()
  File "\Structura-main\structura_core.py", line 81, in generate_with_nametags
    struct2make = structure_reader.process_structure(self.structure_files[model_name]["file"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Structura-main\structure_reader.py", line 37, in __init__
    self.get_blockmap()
  File "\Structura-main\structure_reader.py", line 51, in get_blockmap
    self.cube=self.cube.reshape(self.size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 1907265 into shape (128,116,129)

MCStructure file (change the extension to .mcstructure)
[mmm.zip](https://github.com/user-attachments/files/17667789/mmm.zip)

**Comment by TotallyTung** [comment]
I used https://mcbe-essentials.github.io/structure-editor/ to convert .nbt to mcstructure
