### ISSUE TITLE
Pack creation error: block_name_to_uv

### ISSUE THREAD

**Issue by ForestOfGold** [RavinMaddHatter/Structura#27]
Error coming from my "Everything" structure while attempting to make a .mcpack out of it after removing blocks with missing images. (Those are mentioned in the issue before this one)

![image](https://user-images.githubusercontent.com/77603428/105644777-3be01a00-5e4c-11eb-9e53-0bfc47ce4a7a.png)

```
Traceback (most recent call last):
  File "structura.py", line 96, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 336, in block_name_to_uv
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1883, in __call__
  File "structura.py", line 161, in runFromGui
  File "structura.py", line 99, in generate_pack
  File "armor_stand_class.py", line 74, in make_block
  File "armor_stand_class.py", line 336, in block_name_to_uv
TypeError: unhashable type: 'dict'
```

**Comment by ForestOfGold** [comment]
Does not affect v1.1.1 Pre-release.

**Comment by RavinMaddHatter** [comment]
I am going to close this as it is not in pre 1.1.1
